import type { Model } from "@/lib/models-service";

const now = "2026-01-01T00:00:00.000Z";

export const FALLBACK_MODELS: Model[] = [
  {
    id: "backpack",
    name: "Backpack",
    description: "Static fallback catalog model",
    file_path: "/models/Backpack.glb",
    thumbnail_url: null,
    category: "Bags",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "baseball-caps",
    name: "Baseball Caps",
    description: "Static fallback catalog model",
    file_path: "/models/baseball-caps_UV_FIX.glb",
    thumbnail_url: null,
    category: "Caps",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "baseball-jersey",
    name: "Baseball Jersey",
    description: "Static fallback catalog model",
    file_path: "/models/Baseball-Jersey.glb",
    thumbnail_url: null,
    category: "Baseball",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "basketball-jersey",
    name: "Basketball Jersey and Shorts",
    description: "Static fallback catalog model",
    file_path: "/models/basketball-jersey-and-shorts.glb",
    thumbnail_url: null,
    category: "Jerseys",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "basketball-top-long",
    name: "Basketball Jersey Top And Long Shorts",
    description: "Static fallback catalog model",
    file_path: "/models/basketball-jersey-top-and-long-shorts.glb",
    thumbnail_url: null,
    category: "Jerseys",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "basketball-shirt-long",
    name: "Basketball Shooting Shirt Long Sleeve",
    description: "Static fallback catalog model",
    file_path: "/models/basketball-shooting-shirt-long-sleeve-without-hoodie.glb",
    thumbnail_url: null,
    category: "Jerseys",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "basketball-shirt-hoodie",
    name: "Basketball Shooting Shirt with Hoodie",
    description: "Static fallback catalog model",
    file_path: "/models/basketball-shooting-shirt-short-sleeve-with-hoodie.glb",
    thumbnail_url: null,
    category: "Jerseys",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "basketball-shirt-short",
    name: "Basketball Shooting Shirt Short Sleeve",
    description: "Static fallback catalog model",
    file_path: "/models/basketball-shooting-shirt-short-sleeve-without-a-hoodie.glb",
    thumbnail_url: null,
    category: "Jerseys",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "duffle-bag",
    name: "Duffle Bag",
    description: "Static fallback catalog model",
    file_path: "/models/duffle-bag.glb",
    thumbnail_url: null,
    category: "Bags",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "flag-football-hoodie",
    name: "Flag Football Jersey with Hoodie",
    description: "Static fallback catalog model",
    file_path: "/models/flag-football-top-with-hoodie_UV_MAP_v2.glb",
    thumbnail_url: null,
    category: "Hoodies",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "half-short",
    name: "Half Size Shorts",
    description: "Static fallback catalog model",
    file_path: "/models/half-short.glb",
    thumbnail_url: null,
    category: "Shorts",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "hoodie",
    name: "Hoodie",
    description: "Static fallback catalog model",
    file_path: "/models/Hoodie.glb",
    thumbnail_url: null,
    category: "Hoodies",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "polo-long",
    name: "Polo Shirts Long Sleeve",
    description: "Static fallback catalog model",
    file_path: "/models/polo-shirts-long-sleeve_FIXED.glb",
    thumbnail_url: null,
    category: "Polos",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "polo-short",
    name: "Polo Shirts Short Sleeve",
    description: "Static fallback catalog model",
    file_path: "/models/polo-shirts-short-sleeve_FIXED.glb",
    thumbnail_url: null,
    category: "Polos",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "soccer-crew",
    name: "Soccer Jersey Crew Neck",
    description: "Static fallback catalog model",
    file_path: "/models/soccer-jersey-crew-neck_FIXED.glb",
    thumbnail_url: null,
    category: "Soccer",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "soccer-vneck",
    name: "Soccer Jersey V-Neck",
    description: "Static fallback catalog model",
    file_path: "/models/soccer_jersey_v_neck_COMBINED_FIXED.glb",
    thumbnail_url: null,
    category: "Soccer",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "standard-bottom",
    name: "Baseball Standard Bottom Cut, Cuffed",
    description: "Static fallback catalog model",
    file_path: "/models/standard-bottom-cut-cuffed.glb",
    thumbnail_url: null,
    category: "Shorts",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "track-compression",
    name: "Track & Field Compression Shorts",
    description: "Static fallback catalog model",
    file_path: "/models/track-and-field-compression-shorts.glb",
    thumbnail_url: null,
    category: "Track & Field",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "track-mid-shorts",
    name: "Track & Field Mid-Length Shorts",
    description: "Static fallback catalog model",
    file_path: "/models/track-and-field-mid-len-gth-shorts.glb",
    thumbnail_url: null,
    category: "Track & Field",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "track-split-shorts",
    name: "Track & Field Split Shorts",
    description: "Static fallback catalog model",
    file_path: "/models/track-and-field-split-shorts.glb",
    thumbnail_url: null,
    category: "Track & Field",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "track-crop",
    name: "Track & Field Crop Top",
    description: "Static fallback catalog model",
    file_path: "/models/track-and-field-top-crop-top_FIXED.glb",
    thumbnail_url: null,
    category: "Track & Field",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "track-short-sleeve",
    name: "Track & Field Short Sleeve",
    description: "Static fallback catalog model",
    file_path: "/models/track-and-field-top-short-sleeve.glb",
    thumbnail_url: null,
    category: "Track & Field",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "track-tank",
    name: "Track & Field Tank Top",
    description: "Static fallback catalog model",
    file_path: "/models/track-and-field-top-tank-top_FIXED.glb",
    thumbnail_url: null,
    category: "Track & Field",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "volleyball-long",
    name: "Volleyball Long Sleeve Tops",
    description: "Static fallback catalog model",
    file_path: "/models/volleyball-long-sleeve-tops.glb",
    thumbnail_url: null,
    category: "Volleyball",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "volleyball-short",
    name: "Volleyball Short Sleeve Tops",
    description: "Static fallback catalog model",
    file_path: "/models/volleyball-short-sleeve-tops.glb",
    thumbnail_url: null,
    category: "Volleyball",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "volleyball-spandex-4",
    name: "Volleyball Shorts Spandex 4",
    description: "Static fallback catalog model",
    file_path: "/models/volleyball-shorts-spandex-4.glb",
    thumbnail_url: null,
    category: "Volleyball",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "volleyball-spandex",
    name: "Volleyball Shorts Spandex",
    description: "Static fallback catalog model",
    file_path: "/models/volleyball-shorts-spandex_FIXED.glb",
    thumbnail_url: null,
    category: "Volleyball",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
  {
    id: "volleyball-spandex-alt",
    name: "Volleyball Spandex",
    description: "Static fallback catalog model",
    file_path: "/models/volleyball-spandex.glb",
    thumbnail_url: null,
    category: "Volleyball",
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
    created_by: null,
    file_size: null,
    file_type: "glb",
    tags: ["fallback"],
    metadata: { source: "fallback" },
  },
];

export function getFallbackModels(category?: string | null): Model[] {
  if (!category) return FALLBACK_MODELS;
  return FALLBACK_MODELS.filter((model) => model.category === category);
}
